misc: hpilo: remove unused is_device_reset function
clang with W=1 reports
drivers/misc/hpilo.c:395:19: error: unused function
  'is_device_reset' [-Werror,-Wunused-function]
static inline int is_device_reset(struct ilo_hwinfo *hw)
                  ^
This function is not used, so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20230319170447.1707655-1-trix@redhat.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>