misc: alcor_pci: remove unused alcor functions
clang with W=1 reports
drivers/misc/cardreader/alcor_pci.c:98:20: error: unused function
  'alcor_mask_sd_irqs' [-Werror,-Wunused-function]
static inline void alcor_mask_sd_irqs(struct alcor_pci_priv *priv)
                   ^
drivers/misc/cardreader/alcor_pci.c:103:20: error: unused function
  'alcor_unmask_sd_irqs' [-Werror,-Wunused-function]
static inline void alcor_unmask_sd_irqs(struct alcor_pci_priv *priv)
                   ^
drivers/misc/cardreader/alcor_pci.c:111:20: error: unused function
  'alcor_mask_ms_irqs' [-Werror,-Wunused-function]
static inline void alcor_mask_ms_irqs(struct alcor_pci_priv *priv)
                   ^
drivers/misc/cardreader/alcor_pci.c:116:20: error: unused function
  'alcor_unmask_ms_irqs' [-Werror,-Wunused-function]
static inline void alcor_unmask_ms_irqs(struct alcor_pci_priv *priv)
                   ^
These functions are not used, so remove them.

Signed-off-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20230321000203.1730802-1-trix@redhat.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>