tty/amiserial: Add missing argument for tty_unlock()
commit 73c77a6fef93020fe615ef3e81d11b688b03d8be ("tty_lock: Localise the lock")
missed that 0058ffc5a9a8c0c3233ab7bb40a2f8f0e63e1709 ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>