tracing, net: fix net tree and tracing tree merge interaction
Today's linux-next build (powerpc ppc64_defconfig) failed like this:

 In file included from net/core/skbuff.c:69:
 include/trace/skb.h:4: error: expected ')' before '(' token
 include/trace/skb.h:4: error: expected ')' before '(' token
 [...]

Caused by commit 4f5e413680f0d45cc9cedddf6a179d0cef0f91d8 ("tracing:
replace TP<var> with TP_<var>") from the tracing tree interacting with
commit 09d240a6f8b38a36e2ffc0cc52925958fc79942c ("Network Drop Monitor:
Add trace declaration for skb frees") from the net tree.

Acked-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Ingo Molnar <mingo@elte.hu>