MIPS: alchemy: Fix build error after ioremap cleanup
IOremap changes caused following build error:

arch/mips/alchemy/common/setup.c:99:9: error: implicit declaration of function
+‘remap_pfn_range’; did you mean ‘io_remap_pfn_range’?
+[-Werror=implicit-function-declaration]

Fixed my including linux/mm.h

Fixes: d297cb95b25b ("MIPS: cleanup fixup_bigphys_addr handling")
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>