zorro: Include zorro.h in names.c
The zorro_name_device() function is defined in drivers/zorro/names.c,
but the declaration is not visible there:

    drivers/zorro/names.c:58:13: error: no previous prototype for 'zorro_name_device' [-Werror=missing-prototypes]
       58 | void __init zorro_name_device(struct zorro_dev *dev)

Include the header to avoid the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Geert Uytterhoeven <geert@linux-m68k.org>
Link: https://lore.kernel.org/r/20230810141947.1236730-11-arnd@kernel.org
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>