ARM: mx31_3ds: Fix build due to missing IMX_HAVE_PLATFORM_IMX_SSI
commit 3933ea5 (ARM: mx31_3ds: Add sound support) missed to select IMX_HAVE_PLATFORM_IMX_SSI,
which causes the following build error when only mx31_3ds is selected:

arch/arm/mach-imx/built-in.o: In function `mx31_3ds_init':
mach-mx31_3ds.c:(.init.text+0x15dc): undefined reference to `imx_add_imx_ssi'
mach-mx31_3ds.c:(.init.text+0x16b8): undefined reference to `imx31_imx_ssi_data'

Select IMX_HAVE_PLATFORM_IMX_SSI to fix it.

Signed-off-by: Fabio Estevam <fabio.estevam@freescale.com>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>