sbus: Add prototype for bbc_envctrl_init and bbc_envctrl_cleanup to header
This fixes the following build warning:

	drivers/sbus/char/bbc_envctrl.c:566:5: error: no previous prototype for ‘bbc_envctrl_init’ [-Werror=missing-prototypes]
	  566 | int bbc_envctrl_init(struct bbc_i2c_bus *bp)
	      |     ^~~~~~~~~~~~~~~~
	drivers/sbus/char/bbc_envctrl.c:594:6: error: no previous prototype for ‘bbc_envctrl_cleanup’ [-Werror=missing-prototypes]
	  594 | void bbc_envctrl_cleanup(struct bbc_i2c_bus *bp)
	      |      ^~~~~~~~~~~~~~~~~~~

which in the presence of -Werror=missing-prototypes yields a compiler
error.

Signed-off-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
Reviewed-by: Andreas Larsson <andreas@gaisler.com>
Signed-off-by: Andreas Larsson <andreas@gaisler.com>
Link: https://lore.kernel.org/r/57bc3b43b405431a486162fb8c2558072e976747.1709591118.git.u.kleine-koenig@pengutronix.de