Revert "ARM: dts: mt8135: Add pinctrl/GPIO/EINT node for mt8135."
This reverts commit 4fdb32c368d1564ea94cb832318780b4a0300ebd.

to fix a build error:

arch/arm/boot/dts/mt8135-pinfunc.h:18:40: fatal error: dt-bindings/pinctrl/mt65xx.h: No such file or directory

Signed-off-by: Arnd Bergmann <arnd@arndb.de>