sound: Add delay.h to sound/soc/codecs/sn95031.c
This is further fallout from delay.h removal from asm/apic.h and asm/dma.h:

  96a24eeaed5f: x86: Stop including <linux/delay.h> in two asm header files

Which caused this build failure:

  sound/soc/codecs/sn95031.c: In function ‘sn95031_get_mic_bias’:
  sound/soc/codecs/sn95031.c:153:2: error: implicit declaration of function ‘msleep’ [-Werror=implicit-function-declaration]

Cc: Jean Delvare <khali@linux-fr.org>
Cc: James E.J. Bottomley <James.Bottomley@suse.de>
Cc: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
LKML-Reference: <20110325152014.297890ec@endymion.delvare>
Signed-off-by: Ingo Molnar <mingo@elte.hu>