staging: r8188eu: fix build error
Remove unnecessary label to fix build error introduced with
commit e00097ef2b43 ("staging: r8188eu: remove return from void functions")

drivers/staging/r8188eu/hal/rtl8188e_dm.c:182:1: error: label at end of compound statement

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Michael Straube <straube.linux@gmail.com>
Signed-off-by: Martin Kaiser <martin@kaiser.cx>
Link: https://lore.kernel.org/r/20210805140941.9130-1-straube.linux@gmail.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>