s390/kprobes: define insn cache ops within private header file
clang warns about an unused insn cache ops function:

arch/s390/kernel/kprobes.c:34:1:
  error: unused function 'is_kprobe_s390_insn_slot' [-Werror,-Wunused-function]
DEFINE_INSN_CACHE_OPS(s390_insn);
^
./include/linux/kprobes.h:335:20: note: expanded from macro 'DEFINE_INSN_CACHE_OPS'
static inline bool is_kprobe_##__name##_slot(unsigned long addr)        \
                   ^
<scratch space>:88:1: note: expanded from here
is_kprobe_s390_insn_slot
^

Move the definition to a private header file, which is also similar to
the generic insn cache ops.

Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
Signed-off-by: Alexander Gordeev <agordeev@linux.ibm.com>