m68k: Define __div64_32() to avoid a warning
The generic __div64_32() definition is built on all architectures that
don't provide this as a macro.  m68k however neither defines nor
requires __div64_32, so it should define an empty one to avoid the
warning:

    lib/math/div64.c:31:32: error: no previous prototype for '__div64_32' [-Werror=missing-prototypes]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Geert Uytterhoeven <geert@linux-m68k.org>
Link: https://lore.kernel.org/r/20230809211057.60514-1-arnd@kernel.org
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>