Revert "drm/msm/mdp5: provide dynamic bandwidth management"
This reverts commit 4f9909e839d4e905d89d52fd2f71c43496d42791.

Breaks armv7 build

  ERROR: modpost: "__aeabi_ldivmod" [drivers/gpu/drm/msm/msm.ko] undefined!

Signed-off-by: Rob Clark <robdclark@chromium.org>