Revert "pktgen: Allow configuration of IPv6 source address range"
This reverts commit e106e37acf9b947be1ad1af6f236b7fc7b2d2d9a.

It causes build failures on 32-bit, for example:

   net/core/pktgen.o: In function `mod_cur_headers':
>> pktgen.c:(.text.mod_cur_headers+0xba0): undefined reference to `__umoddi3'

Signed-off-by: David S. Miller <davem@davemloft.net>