m68knommu: fix broken use of BUAD_TABLE_SIZE in 68328serial driver
Commit 505d7d6b388ae9a691dabb9bb2f9b52f231bb221 ("serial: 68328serial.c:
remove BAUD_TABLE_SIZE macro") misses one use of BAUD_TABLE_SIZE. So the
resulting 68328serial.c does not compile:

drivers/serial/68328serial.c: In function ‘m68328_console_setup’:
drivers/serial/68328serial.c:1439: error: ‘BAUD_TABLE_SIZE’ undeclared (first use in this function)
drivers/serial/68328serial.c:1439: error: (Each undeclared identifier is reported only once
drivers/serial/68328serial.c:1439: error: for each function it appears in.)

Fix that last use of it.

Signed-off-by: Greg Ungerer <gerg@uclinux.org>
Cc: <stable@kernel.org>