media: Revert "[media] Terratec Cinergy S2 USB HD Rev.2"
This reverts commit e347ee4f6b9fcf2f099bd198895b1fba3a67b7d4.

drivers/media/dvb/dvb-usb/dw2102.c:1478:18: error: ‘USB_PID_TEVII_S421’ undeclared here (not in a function)
drivers/media/dvb/dvb-usb/dw2102.c:1479:18: error: ‘USB_PID_TEVII_S632’ undeclared here (not in a function)

Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>