mt76: mt7921: fix mt7921s Kconfig
Add missing MMC dependency in mt7921s Kconfig:

ld: drivers/net/wireless/mediatek/mt76/sdio.o: in function `mt76s_rr':
sdio.c:(.text+0x1263): undefined reference to `sdio_claim_host'
ld: sdio.c:(.text+0x1278): undefined reference to `sdio_writel'
ld: sdio.c:(.text+0x12c8): undefined reference to `sdio_writel'
ld: sdio.c:(.text+0x1327): undefined reference to `sdio_readl'
ld: sdio.c:(.text+0x134d): undefined reference to `sdio_writel'
ld: sdio.c:(.text+0x138c): undefined reference to `sdio_readl'
ld: sdio.c:(.text+0x140f): undefined reference to `sdio_readl'
ld: sdio.c:(.text+0x1498): undefined reference to `sdio_readl'
ld: sdio.c:(.text+0x14e5): undefined reference to `sdio_release_host'
ld: drivers/net/wireless/mediatek/mt76/sdio.o: in function `mt76s_wr':
sdio.c:(.text+0x1599): undefined reference to `sdio_claim_host'
ld: sdio.c:(.text+0x15ae): undefined reference to `sdio_writel'
ld: sdio.c:(.text+0x15f9): undefined reference to `sdio_writel'
ld: sdio.c:(.text+0x1646): undefined reference to `sdio_writel'
ld: sdio.c:(.text+0x16a5): undefined reference to `sdio_readl'
ld: sdio.c:(.text+0x16cb): undefined reference to `sdio_writel'
ld: sdio.c:(.text+0x170a): undefined reference to `sdio_readl'
ld: sdio.c:(.text+0x1782): undefined reference to `sdio_readl'
ld: sdio.c:(.text+0x17e9): undefined reference to `sdio_release_host'

Fixes: 5bc12d0e71774 ("mt76: mt7921: introduce mt7921s support")
Reported-by: Randy Dunlap <rdunlap@infradead.org>
Tested-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Lorenzo Bianconi <lorenzo@kernel.org>
Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/1ce6cb04ba1ab5aabd2b06b45fd8266537ef5359.1634893214.git.lorenzo@kernel.org