Revert "net: dccp: initialize (addr,port) listening hashtable"
This reverts commit 4d62eafe6f34b3ac113218556fab58d8baae9ee8.

Cause build failures when DCCP is modular.

ERROR: "inet_hashinfo2_init" [net/dccp/dccp.ko] undefined!

Signed-off-by: David S. Miller <davem@davemloft.net>