Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit c95ca3e8bf2232115868bfccf3f81c2aa0b096de.

Commit c95ca3e8bf22 results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: c95ca3e8bf22 ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>