Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit a410292ef0a49c300ccf2236cdcd39e413bfbd69, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer