m68k: Add missing types to asm/irq.h
As reported in commit 8dbf9e57ac2d ("net: sunhme: move asm includes to
below linux includes") when including this <asm/*> header before the
needed <linux/*> headers the compilation will fail because of missing
types:

    arch/m68k/include/asm/irq.h:66:20: warning: ‘struct pt_regs’ declared inside parameter list will not be visible outside of this definition or declaration
       66 |             struct pt_regs *));
	  |                    ^~~~~~~
    arch/m68k/include/asm/irq.h:78:11: error: expected ‘;’ before ‘void’
       78 | asmlinkage void do_IRQ(int irq, struct pt_regs *regs);
	  |           ^~~~~
	  |           ;
    arch/m68k/include/asm/irq.h:78:40: warning: ‘struct pt_regs’ declared inside parameter list will not be visible outside of this definition or declaration
       78 | asmlinkage void do_IRQ(int irq, struct pt_regs *regs);
	  |                                        ^~~~~~~
    arch/m68k/include/asm/irq.h:79:8: error: unknown type name ‘atomic_t’
       79 | extern atomic_t irq_err_count;
	  |        ^~~~~~~~

Signed-off-by: Rolf Eike Beer <eike-kernel@sf-tec.de>
Reviewed-by: Geert Uytterhoeven <geert@linux-m68k.org>
Link: https://lore.kernel.org/r/5971770.lOV4Wx5bFT@eto.sf-tec.de
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>