[ARM] 4530/1: MXC: fix elf_hwcap compile breakage as in iop13xx
MXC needs the same change as IOP.  See [ARM] 4494/1
or commit e570e3505480800671656927e51215eea5ddcda5

An undefined reference to elf_hwcap prevents linkage, due
to changes made by 552c09879cc30710b478946191f5535c1f7c4f3c
and 245215864fccee0da07e094f8fac6b5800f22908

Removing processor.h removes the extern definition of
elf_hwcap, which fixes the link issue, but forgets cpu_relax().
So, instead, we'll call barrier() directly.

Cc: Lennert Buytenhek <kernel@wantstofly.org>
Cc: Catalin Marinas <catalin.marinas@arm.com>
Acked-by: Ross Wille <wille@freescale.com>
Signed-off-by: Quinn Jensen <quinn.jensen@freescale.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>