Revert "firmware: qcom: scm: Add support for MC boot address API"
This reverts commits 719be9b6d2e2 and d93cda32fb3f, since this still
causes a build failure when QCOM_SCM is a loadable module, or when
CONFIG_SMP is disabled:

ERROR: modpost: "cpu_logical_map" [drivers/firmware/qcom-scm.ko] undefined!

This be done better for 5.17, but it's too late now to rework
properly.

Fixes: d93cda32fb3f ("firmware: qcom: scm: Don't break compile test on non-ARM platforms")
Fixes: 719be9b6d2e2 ("firmware: qcom: scm: Add support for MC boot address API")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>